name: book_meter
description: A book tracking and logging application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  image_picker: ^1.0.4
  floating_search_bar: ^0.3.0
  intl: ^0.18.1
  flushbar: ^1.10.4
  in_app_purchase: ^3.1.11
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/logo.png